version: '3'
services: 
  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - node-network
networks: 
  node-network:
    driver: bridge      
